repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.5.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
          - id: check-added-large-files

    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.4.5
      hooks:
        - id: ruff
          args: [ --fix,  --config=pyproject.toml ]
        - id: ruff-format
          args: [ --config=pyproject.toml ]

    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v1.10.0
      hooks:
          - id: mypy
            args: [--no-strict-optional, --ignore-missing-imports]
